version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - andreafalzetti
  ignore:
  - dependency-name: documentation
    versions:
    - 13.1.1
    - 13.2.0
    - 13.2.1
    - 13.2.4
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: "@semantic-release/npm"
    versions:
    - 7.0.10
    - 7.1.0
  - dependency-name: semantic-release
    versions:
    - 17.4.0
    - 17.4.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
  - dependency-name: joi
    versions:
    - 17.3.0
