language: node_js
node_js:
- '12'
before_install:
- sudo apt-get update -y
- npm install -g npm@latest
before_script:
- npm ci
script:
- npm test
- npm run lint
- npm run build
- npx semantic-release
notifications:
  email:
    recipients:
    - andrea@falzetti.me
    on_success: change
    on_failure: always
env:
  global:
  - secure: YbQ8pI53tqVwl+tiW12cDzjknGiYjGbEH/5EZUsOhSPB29an87CeJ0VO+CeES2ym5UbaUMwa8T1y/RyjIphLz+DXl4Wry5zy83gCIVA+WKc7xldkRvBgl49PSLX3qX5s2Yo/UKpN8sMDCn0/FZObFLP4U9nJpdq3Y+CIUb8sOIT+XlUZ9TZRC1TMIG7X54i/hOYBzX6YviKEuT5v6uFDivzNJcpCuODvCHHsgLjSXT/a+EMRBcVOIOcUSSdOxJM7CFP43PY2iasHUM+3mcBYoOkklN2qIZw4xrHAq0QCCOBlpbwMa1Wo69Ck95++c+wLmieJCPqcVa7SwTzUQ1fwZe0/upXWQ7da8k4N0UfPGA3oN/2w0fRiB8f6AjmCd+s0eiqibnPExqPof64JPttZZSZdbLpuVr2qD5I8SaJcrfaIce5vcNfhXTJMo7SJwg+xSQXeV+zS5Wh1Bi/p1tEmg8N6cSU1l2haBLDcerX7cxSOaCzT2ZFVmfgW3+rTaqmNKuJoRlACQiQt9NMXFOmaFEa6VHQ6601Ji3zwromks25N66Un4GMzJP+XKq4WgDdtFgW1HsuGMM/uLh2IB7mcSG3KFUk+YDGF/6SxuE3zXMuMal8U+mRhlHWNshRkAS+7Tc/BHmUaH+hpbByfMPjDYfvQud0TSYYaeuklN6AsmGI=
  - secure: DiGYNS02lc9bFs4Q36JxpGOV/j0i8nrJp1Cs6iVpoRZOMfK3P+BoYh08Yuthn3/7rrI8oxx3iQ+6fhLProeOM0EyIHSL/NS2yPvZDX8lgquBoqqgCEIdq7q1wX/Y+WWptUAnLlMLR9HYUxtuYebCRTu183lotrLQXTpzmWbugzobvhwGgnumTZ8LWgGIVj98/44NJG1xhA2P57XIVgdRPFyyVV/ecgUd1u0jtiyffZ6Laxcqc1LSVf1nxP6LvB0o6MkB4xoc5N1RsY2Yall2f5uMVh5m0W5X+c/Q64NWzwk0x3WTIDORkIUB2H4KA8DqmdgWiGWM0IR5Fpz6tTayVORMpp+9TyVzcZe6atczKXZgCoE7gWlCyYoOb4X+g1QgPZx9g/2HY77zeLhbL5aDf12WxtBc6RxCsX9SUi7wMOPRWQgRecZQ2iNq2E19624J8YA5ZBwF6BQDmS6Z8zT7WIo6kjLN311kHuRnJbcAHSEEdDkADAjul4Ew57ZK/RB/scz/mNAyL7cnZjVBmFnyhVY09utliwCmk7NTYVRb84DPjLGC2ZljvGvLK0oBMASEncSl8XPsjtysvo1LC1p/liGIL6y6tL4OfAbcANWwveplYnRunxeENEIVQMAWGI7K8nqTg6G9T8oj6elFkQOhSEFiWtcYXiHPR58vwxYZ/2M=
